[build]
builder = "nixpacks"

[deploy]
startCommand = "python bot.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app" 